//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiEmployee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrudEmployeedb
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Aderess { get; set; }
        public string Designation { get; set; }
        public decimal Salary { get; set; }
    }
}
